### PR TITLE
Add methods to Create Images & Play Sounds

### PR DESCRIPTION
**Pull request by ExplorerDonutz**
Added methods to create images without having to write long lines of code every time, as well as the ability to play sounds both looping and non-looped.

### CODE REVIEW

**Comment by salamander2** [comment]
Thanks for doing this.

It's really too bad that your two commits have exactly the same comment on them. Github doesn't do timestamps so I had to go to Insights/Network to see which hash is the most recent commit.

It's also too bad that whatever IDE you're using reformatted the whole 2000 lines. This makes it hard for me to see what exactly the changes are. I did see it somewhere, but now I can't remember what option I used to see it. What I'm looking at now shows ALL the changes, including whitespace changes.  :(

**Comment by salamander2** [comment]
Are these the changes that you made?

``` /**
     * Plays a sound in loop
     *
     * @param url The file location of the sound
     */
    public synchronized void playSoundLoop(final String url) {
        new Thread(new Runnable() {
            public void run() {
                try {
                    Clip clip = AudioSystem.getClip();
                    AudioInputStream inputStream = AudioSystem.getAudioInputStream(
                            this.getClass().getClassLoader().getResourceAsStream(url));
                    clip.open(inputStream);
                    clip.loop(Clip.LOOP_CONTINUOUSLY);
                    ;
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        }).start();
    }

    /**
     * Plays a sound
     *
     * @param url The file location of the sound
     */
    public synchronized void playSound(final String url) {
        new Thread(new Runnable() {
            public void run() {
                try {
                    Clip clip = AudioSystem.getClip();
                    AudioInputStream inputStream = AudioSystem.getAudioInputStream(
                            this.getClass().getClassLoader().getResourceAsStream(url));
                    clip.open(inputStream);
                    clip.start();
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        }).start();
    }

    /**
     * Create an image without having to write the entire line of code every time you need an image
     *
     * @param url The filename of the image
     * @return Returns the image
     */
    public Image createImage(String url) {
        final Image image = Toolkit.getDefaultToolkit().getImage(this.getClass().getClassLoader().getResource(url));
        return image;
    }
```

**Comment by salamander2** [comment]
So ... about these changes. The whole point of this package is to get students up and running so that they can program quickly using graphics. It's not really meant to be used for more than a semester. 

The **playSound()** is a great idea. However, it kind of conflicts with the above goal.  I don't want to end up concealing too many things from the novice user. Almost everything done in HSA2 can be done right in Swing. The exceptions are:

* setStroke (it's a little more complicated in Swing)
* setAntiAlias (it requires about 3 lines in Swing to do this)
* showDialog (the actual syntax of JOptionPanes is more complicated)

These three things add significant benefits to graphics programs so that I don't feel bad about including them (and concealing the true Swing code).      
The mouse and keyboard handlers are special and don't translate into Swing at all, but without them there would be no interactivity.

**Playing sound** is an extra thing. I think that it is something that students could easily learn, and if they every want to play sound in a non-HSA2 program, they would have to learn the syntax.   So I don't want to incorporate that change into the main HSA2 code.  Two options: (i) make another branch that has this stuff, (ii) include a short demo program to show how it's done.

Thank you so much for doing this!  I will definitely update my notes with your code.

---------------

You also have a "createImage()" method. This looks like it is actually a "loadImage()" method. Create image would be something like this:

`img = new BufferedImage(panW,panH, BufferedImage.TYPE_INT_RGB);`  (from http://quarkphysics.ca/ICS4U1/javaprogs/unit4/Spiral.java).

This does motivate me to go back and write clear and comprehensive notes on loading images. The problem with just including your one method is that there are a number of different ways of loading images. I suspect that we always want a BufferedImage rather than an image, but I'll have to look into it.  I also don't know if Toolkit is a better way to go than other ways.

Once I've done this, I think that I will indeed add a method for simply loading an image. It would indeed make it simpler for the students and loading images is an important thing to do.

Thank you again!

**Comment by ExplorerDonutz** [comment]
Thanks for checking out my pull request. Firstly I'd like to apologize about the reformatting. It was likely a mistake on my part. For the createImage() method I would have to agree, loadImage() would be a more appropriate name for the method. As for my choice in using toolkit isn't so much that it's better, but rather what happens to be taught in the class I am in. I believe that BufferedImage would be a better option overall, so thanks for pointing that out! Overall this has been really helpful, and I plan to apply your suggestions to my code. Thanks for the help, and keep up the good work with HSA2, I know my teacher really appreciates it!

**Comment by salamander2** [comment]
@ExplorerDonutz 

I'm now looking at the playSound methods and have some questions. I'd really appreciate any help you can give.

This is your code:

```
    /**
     * Plays a sound
     *
     * @param url The file location of the sound
     */
    public synchronized void playSound(final String url) {
        new Thread(new Runnable() {
            public void run() {
                try {
                    Clip clip = AudioSystem.getClip();
                    AudioInputStream inputStream = AudioSystem.getAudioInputStream(
                            this.getClass().getClassLoader().getResourceAsStream(url));
                    clip.open(inputStream);
                    clip.start();
                } catch (Exception e) {
                    System.err.println(e.getMessage());
                }
            }
        }).start();
    }
```

1. Why does it have to be synchronized? What happens if it isn't?
2. Why does String URL have to be final? I haven't seen this in method parameters. (Also Strings are immutable anyway.)
3. I tried this without the Thread and it seems to work just the same. In other words, I tried: 

```
public synchronized void playSound(final String url) {       
    try {
        Clip clip = AudioSystem.getClip();
        AudioInputStream inputStream = AudioSystem.getAudioInputStream(
                this.getClass().getClassLoader().getResourceAsStream(url));
        clip.open(inputStream);
        clip.start();
    } catch (Exception e) {
        System.err.println(e.getMessage());
    }
}
```

and the audio clip still played. I was also able to play multiple sounds at once.  So why are you using a Thread? Is it needed for some reason?

Finally, there is one error:

` } catch (Exception e) { `

Don't do this!
You must always specify the exact error that you're trying to catch and list the most specific errors first. If you're trying to catch every possible error that Java can throw, then your code is not well written

If you look at my notes on this (http://quarkphysics.ca/ICS3U1/unit4/Sound.html)
I have `} catch(UnsupportedAudioFileException | IOException | LineUnavailableException ex) {`

**Comment by salamander2** [comment]
:gift:  Okay, I found out about "final" in method parameters.  
https://stackoverflow.com/questions/500508/why-should-i-use-the-keyword-final-on-a-method-parameter-in-java/10380512
Use it only on long complicated methods, where one might reassign the argument parameter inadvertently.

**Pull request closed without merging**
